from .. import Device, Component as Cpt
from . import plugin_versions


class CommonPlugins(Device):
    ...


class CommonPlugins_V20(CommonPlugins, version=(2, 0), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V20

    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    magick1 = Cpt(plugins.MagickPlugin, "Magick1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")


class CommonPlugins_V21(CommonPlugins, version=(2, 1), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V21

    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    magick1 = Cpt(plugins.MagickPlugin, "Magick1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")


class CommonPlugins_V22(CommonPlugins, version=(2, 2), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V22

    attr1 = Cpt(plugins.CommonAttributePlugin, "Attr1:")
    cb1 = Cpt(plugins.CircularBuffPlugin, "CB1:")
    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    magick1 = Cpt(plugins.MagickPlugin, "Magick1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    roistat1 = Cpt(plugins.CommonROIStatPlugin, "ROIStat1:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")


class CommonPlugins_V23(CommonPlugins, version=(2, 3), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V23

    attr1 = Cpt(plugins.CommonAttributePlugin, "Attr1:")
    cb1 = Cpt(plugins.CircularBuffPlugin, "CB1:")
    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    magick1 = Cpt(plugins.MagickPlugin, "Magick1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    roistat1 = Cpt(plugins.CommonROIStatPlugin, "ROIStat1:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")


class CommonPlugins_V24(CommonPlugins, version=(2, 4), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V24

    attr1 = Cpt(plugins.CommonAttributePlugin, "Attr1:")
    cb1 = Cpt(plugins.CircularBuffPlugin, "CB1:")
    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    magick1 = Cpt(plugins.MagickPlugin, "Magick1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    roistat1 = Cpt(plugins.CommonROIStatPlugin, "ROIStat1:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")


class CommonPlugins_V25(CommonPlugins, version=(2, 5), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V25

    attr1 = Cpt(plugins.CommonAttributePlugin, "Attr1:")
    cb1 = Cpt(plugins.CircularBuffPlugin, "CB1:")
    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    magick1 = Cpt(plugins.MagickPlugin, "Magick1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    roistat1 = Cpt(plugins.CommonROIStatPlugin, "ROIStat1:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")


class CommonPlugins_V26(CommonPlugins, version=(2, 6), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V26

    attr1 = Cpt(plugins.CommonAttributePlugin, "Attr1:")
    cb1 = Cpt(plugins.CircularBuffPlugin, "CB1:")
    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    magick1 = Cpt(plugins.MagickPlugin, "Magick1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    roistat1 = Cpt(plugins.CommonROIStatPlugin, "ROIStat1:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")


class CommonPlugins_V31(CommonPlugins, version=(3, 1), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V31

    attr1 = Cpt(plugins.CommonAttributePlugin, "Attr1:")
    cb1 = Cpt(plugins.CircularBuffPlugin, "CB1:")
    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    fft1 = Cpt(plugins.FFTPlugin, "FFT1:")
    gather1 = Cpt(plugins.CommonGatherPlugin, "Gather1:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    roistat1 = Cpt(plugins.CommonROIStatPlugin, "ROIStat1:")
    scatter1 = Cpt(plugins.ScatterPlugin, "Scatter1:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")


class CommonPlugins_V32(CommonPlugins, version=(3, 2), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V32

    attr1 = Cpt(plugins.CommonAttributePlugin, "Attr1:")
    cb1 = Cpt(plugins.CircularBuffPlugin, "CB1:")
    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    fft1 = Cpt(plugins.FFTPlugin, "FFT1:")
    gather1 = Cpt(plugins.CommonGatherPlugin, "Gather1:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    roistat1 = Cpt(plugins.CommonROIStatPlugin, "ROIStat1:")
    scatter1 = Cpt(plugins.ScatterPlugin, "Scatter1:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")


class CommonPlugins_V33(CommonPlugins, version=(3, 3), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V33

    attr1 = Cpt(plugins.CommonAttributePlugin, "Attr1:")
    cb1 = Cpt(plugins.CircularBuffPlugin, "CB1:")
    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    fft1 = Cpt(plugins.FFTPlugin, "FFT1:")
    gather1 = Cpt(plugins.CommonGatherPlugin, "Gather1:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    proc1_tiff = Cpt(plugins.TIFFPlugin, "Proc1:TIFF:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    roistat1 = Cpt(plugins.CommonROIStatPlugin, "ROIStat1:")
    scatter1 = Cpt(plugins.ScatterPlugin, "Scatter1:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats1_ts = Cpt(plugins.TimeSeriesPlugin, "Stats1:TS:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats2_ts = Cpt(plugins.TimeSeriesPlugin, "Stats2:TS:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats3_ts = Cpt(plugins.TimeSeriesPlugin, "Stats3:TS:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats4_ts = Cpt(plugins.TimeSeriesPlugin, "Stats4:TS:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    stats5_ts = Cpt(plugins.TimeSeriesPlugin, "Stats5:TS:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")


class CommonPlugins_V34(CommonPlugins, version=(3, 4), version_of=CommonPlugins):
    plugins = plugin_versions.PluginVersions_V34

    attr1 = Cpt(plugins.CommonAttributePlugin, "Attr1:")
    cb1 = Cpt(plugins.CircularBuffPlugin, "CB1:")
    cc1 = Cpt(plugins.ColorConvPlugin, "CC1:")
    cc2 = Cpt(plugins.ColorConvPlugin, "CC2:")
    codec1 = Cpt(plugins.CodecPlugin, "Codec1:")
    codec2 = Cpt(plugins.CodecPlugin, "Codec2:")
    fft1 = Cpt(plugins.FFTPlugin, "FFT1:")
    gather1 = Cpt(plugins.CommonGatherPlugin, "Gather1:")
    hdf1 = Cpt(plugins.HDF5Plugin, "HDF1:")
    jpeg1 = Cpt(plugins.JPEGPlugin, "JPEG1:")
    netcdf1 = Cpt(plugins.NetCDFPlugin, "netCDF1:")
    nexus1 = Cpt(plugins.NexusPlugin, "Nexus1:")
    over1 = Cpt(plugins.CommonOverlayPlugin, "Over1:")
    proc1 = Cpt(plugins.ProcessPlugin, "Proc1:")
    proc1_tiff = Cpt(plugins.TIFFPlugin, "Proc1:TIFF:")
    roi1 = Cpt(plugins.ROIPlugin, "ROI1:")
    roi2 = Cpt(plugins.ROIPlugin, "ROI2:")
    roi3 = Cpt(plugins.ROIPlugin, "ROI3:")
    roi4 = Cpt(plugins.ROIPlugin, "ROI4:")
    roistat1 = Cpt(plugins.CommonROIStatPlugin, "ROIStat1:")
    scatter1 = Cpt(plugins.ScatterPlugin, "Scatter1:")
    stats1 = Cpt(plugins.StatsPlugin, "Stats1:")
    stats1_ts = Cpt(plugins.TimeSeriesPlugin, "Stats1:TS:")
    stats2 = Cpt(plugins.StatsPlugin, "Stats2:")
    stats2_ts = Cpt(plugins.TimeSeriesPlugin, "Stats2:TS:")
    stats3 = Cpt(plugins.StatsPlugin, "Stats3:")
    stats3_ts = Cpt(plugins.TimeSeriesPlugin, "Stats3:TS:")
    stats4 = Cpt(plugins.StatsPlugin, "Stats4:")
    stats4_ts = Cpt(plugins.TimeSeriesPlugin, "Stats4:TS:")
    stats5 = Cpt(plugins.StatsPlugin, "Stats5:")
    stats5_ts = Cpt(plugins.TimeSeriesPlugin, "Stats5:TS:")
    tiff1 = Cpt(plugins.TIFFPlugin, "TIFF1:")
    trans1 = Cpt(plugins.TransformPlugin, "Trans1:")
